
<!DOCTYPE html>

<html lang="en">

<head>
   <title>Cookies</title>
   <meta charset="UTF-8">
   <meta name="description" content="An online newspaper where you can register/log-in and you are remembered with cookies">
   <meta name="author" content="Katsiaryna Aliashkevich">
   <link href="cookies.css" rel="stylesheet">
   <link rel="icon" href="logo.png">
</head> 

<body style="background-color: #333">

   <div id="container">
   <div class="top">
      <header>
         <!-- Banner Content -->
         <div class="top">
           <!-- left -->
           <div>
             <h1><a href="https://www.utexas.edu"><img class="logo" src="logo.png" alt="The Daily Clarion logo"></a>The Daily Clarion</h1>
             <h4>
            <?php
                $time = date("l jS \of F Y");
                print $time;
            ?>
            <br>  Austin,TX </h4>
           </div>
         </div>
       </header>
   </div>
   
   <div id="content">
      <div>
         <h3>Major Headlines of the Day</h3>
            <table style="width:100%">
               <tr>
                  <th><a href="environment.php">A Looming Environmental Catastrophe</a></th>
                  <td><img src="climate.png" alt="Picture of deforestation"> Deforestation</td>
               </tr>
               <tr>
                  <th><a href="tesla.php">Tesla Surpasses $1 trillion Market Capitalization</a></th>
                  <td><img src="tesla.png" alt="Picture of a Tesla"> Tesla</td>
               </tr>
               <tr>
                  <th><a href="aiart.php">The Rise of AI in Art</a></th>
                  <td><img src="art.png" alt="Picture of AI Art"> AI Art</td>
               </tr>
               <tr>
                  <th><a href="subway.php">Major Subway Expansion Project Approved by City Council</a></th>
                  <td><img src="metro.png" alt="Picture of New York's subway expansion project"> New York's subway expansion project</td>
               </tr>
               <tr>
                  <th><a href="festival.php">Music Festival Lineup Announced</a></th>
                  <td><img src="festival.png" alt="Picture of music festival"> Music Festival</td>
               </tr>
            </table>
      </div>
      <hr>
   </div>
   <div id="footer">
   <div style="text-align: center">
   <a href="mailto:katrinaaliashkevich@gmail.com">Contact</a>
   © Katsiaryna Aliashkevich  <br>(Images and text generated by OpenSource AI)
   </div>
   </div>

</body>
</html>

